### ISSUE TITLE
Use of "normal" for things that aren't distributions

### ISSUE THREAD

**Issue by b-steve** [david-borchers/SCR-Book#1]
We often use the word "normal" to explain the shape of the halfnormal detection function. For example, "To do this, let's assume that the encounter rate function has the shape of a normal distribution" (line 62, ERdetfun.Rnw), and "Notice that while the encounter rate model was specified to have normal shape" (line 139, ERdetfun.Rnw).

Is there a risk this will be misinterpreted as either
* Something being "normally distributed", or
* Something being of a "typical/usual" shape?

Alternatively, could we say something like "let's assume that the encounter rate function is a Gaussian function", or maybe "let's assume that the encounter rate function is a bell-shaped curve"?

**Comment by david-borchers** [comment]
Yes, I was aware of that issue when writing, but unsure what to do about it. Since it struck you as possibly a problem, we should do something about it. “Halfnormal” instead of “normal” would do the trick, but I am uneasy about this because when thinking of the detection function on a plane, it is not “half” at all – it is only “half” when you think of it only in the distance dimension.

Maybe “shape of a Gaussian distribution” and “Gaussian distribution shape” is best? I’ll check with you at coffee now and then change the text.

David
--
David Borchers

Head of Statistics Division
School of Mathematics and Statistics
Centre for Research into Ecological and Environmental Modelling
The Observatory, Buchanan Gardens ph: (+44) 1334 461843
University of St Andrews fax:(+44) 1334 461800
Fife, KY16 9LZ, Scotland
email: dlb@mcs.st-and.ac.uk<mailto:dlb@mcs.st-and.ac.uk>
www: http://www.creem.st-and.ac.uk/dlb/dlb.html

The University of St Andrews is a charity registered in Scotland: No SC013532
